git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_5/cascade_oldformat_3.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_2.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_16.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_26.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_27.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_32.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_37.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_42.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_44.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_oldformat_45.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_oldformat_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_oldformat_8.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_oldformat_15.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_oldformat_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_oldformat_8.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_oldformat_15.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_oldformat_19.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_oldformat_24.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_oldformat_5.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_oldformat_12.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_oldformat_13.xml

git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_5/cascade_3.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_2.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_16.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_26.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_27.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_32.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_37.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_42.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_44.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_6/cascade_45.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_8.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_7/cascade_15.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_4.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_8.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_15.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_19.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_8/cascade_24.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_5.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_12.xml
git rm -f /home/ubuntu/2015VisionCode/cascade_training/classifier_bin_9/cascade_13.xml
